In [1]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr [8]

np.int64(8)

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] =100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_array = arr[0:6]

In [18]:
slice_of_array[:] = 99

In [19]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:] = 100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0,0]

np.int64(5)

In [29]:
arr_2d[0]

array([ 5, 10, 15])

In [32]:
arr_2d[1,2]

np.int64(30)

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [36]:
arra = np.arange(1,11)

In [37]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr >5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [39]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
boolean = arra > 5

In [41]:
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arra[arra > 5]

array([ 6,  7,  8,  9, 10])